=== saida-ben/xml/scolarite.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <!-- Definition of simple types -->
  <xs:simpleType name="SexeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Masculin"/>
      <xs:enumeration value="Feminin"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TeleType">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="EmailType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Personnel"/>
      <xs:enumeration value="Academique"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Definition of complex types -->
  <xs:element name="Scolarite">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Enseignants"/>
         <xs:element ref="Etudiants"/>
          <xs:element ref="Modules"/>
           <xs:element ref="Matieres"/>
           <xs:element ref="notes"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Nom" type="xs:string"/>
  <xs:element name="CIN" type="xs:ID"/>
  <xs:element name="Sexe" type="SexeType"/>
  <xs:element name="Prenom" type="xs:string"/>
  <xs:element name="Tele" type="TeleType"/>
  <xs:element name="dateNaiss" type="TeleType"/>
  <xs:element name="codeModule" type="xs:ID"/>
  <xs:element name="cordonnateur" type="xs:IDREF"/>
  
    <xs:element name="codeMatiere" type="xs:ID"/>
    <xs:element name="intitule" type="xs:string"/>
    <xs:element name="coeff" type="xs:string"/>
    

  <xs:element name="Email">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="Type" type="EmailType" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
<xs:element name="adresse">
<xs:complexType>
<xs:sequence>
<xs:element name="rue"/>
<xs:element name="numero"/>
<xs:element name="ville"/>
</xs:sequence>
</xs:complexType>
</xs:element>


    <xs:element name="note">
      <xs:complexType>
    <xs:sequence>
      <xs:element name="NoteType"/>
      <xs:element name="valeur" type="xs:string"/>
    </xs:sequence>
            <xs:attribute name="NInsc" type="xs:IDREF" use="required"/>
          <xs:attribute name="codeMatiere" type="xs:IDREF" use="required"/>
   </xs:complexType>
   </xs:element>

   <xs:element name="notes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="note" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:simpleType name="NoteType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DS"/>
      <xs:enumeration value="Examen"/>
    </xs:restriction>
  </xs:simpleType>

<xs:element name="Module">
    <xs:complexType>
    <xs:sequence>
    <xs:element name="Nom"/>
    </xs:sequence>
      <xs:attribute name="codeModule" type="xs:ID" use="required"/>
      <xs:attribute name="NSom" type="xs:IDREF" use="required"/>
    </xs:complexType>
     </xs:element>

     <xs:element name="Modules">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="Module" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:complexType>
    </xs:element>

    <xs:element name="Matiere">
    <xs:complexType>
    <xs:sequence>
    <xs:element name="intitule"/>
    <xs:element name="coeff"/>
    </xs:sequence>
          <xs:attribute name="NSom" type="xs:IDREF" use="required"/>
          <xs:attribute name="codeModule" type="xs:IDREF" use="required"/>
          <xs:attribute name="codeMatiere" type="xs:ID" use="required"/>
    </xs:complexType>
     </xs:element>
     
  <xs:element name="Enseignants">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Enseignant" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Matieres">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Matiere" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Enseignant">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="CIN"/>
        <xs:element ref="Sexe"/>
        <xs:element ref="Nom"/>
        <xs:element ref="Prenom"/>
        <xs:element ref="Teles"/>
        <xs:element ref="Emails"/>
      </xs:sequence>
      <xs:attribute name="NSom" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>
  
 <xs:element name="Etudiants">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Etudiant" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="Emails">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Email" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
   <xs:element name="Teles">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Tele" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
<xs:element name="Etudiant">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="CIN"/>
        <xs:element ref="Sexe"/>
        <xs:element ref="Prenom"/>
        <xs:element ref="Nom"/>
        <xs:element ref="Teles"/>
        <xs:element ref="Emails"/>
        <xs:element ref="dateNaiss"/>
        <xs:element ref="adresse" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="NInsc" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>


</xs:schema>

=== saida-ben/xml/scolarite.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="scolarite.xsl"?>
<?xml-stylesheet type="text/xsl" href="style.css"?>
<Scolarite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scolarite.xsd">
<Enseignants>
  <Enseignant NSom="E123">
    <CIN>HH123456789</CIN>
    <Sexe>Masculin</Sexe>
    <Nom>Doe</Nom>
    <Prenom>John</Prenom>
    <Teles>
      <Tele>1234</Tele>
      <Tele>98765</Tele>
    </Teles>
    <Emails>
      <Email Type="Personnel">john.doe@example.com</Email>
      <Email Type="Academique">john.doe@university.edu</Email>
    </Emails>
  </Enseignant>
  <Enseignant NSom="E124">
    <CIN>HH85026</CIN>
    <Sexe>Feminin</Sexe>
    <Nom>BENZARIYA</Nom>
    <Prenom>Saida</Prenom>
    <Teles>
      <Tele>06273737</Tele>
      <Tele>06273737</Tele>
    </Teles>
    <Emails>
      <Email Type="Personnel">john.doe@example.com</Email>
      <Email Type="Academique">john.doe@university.edu</Email>
    </Emails>
   
  </Enseignant>
</Enseignants>
<Etudiants>
  <Etudiant NInsc="S456">
    <CIN>HH987321</CIN>
    <Sexe>Feminin</Sexe>
    <Prenom>Jane</Prenom>
    <Nom>soso</Nom>
    <Teles>
      <Tele>555-555-5555</Tele>
    </Teles>
    <Emails>
      <Email Type="Personnel">jane.smith@example.com</Email>
    </Emails>
    <dateNaiss>2000-01-01</dateNaiss>
      <adresse>
        <rue>Main Street</rue>
        <numero>123</numero>
        <ville>Cityville</ville>
      </adresse>
  </Etudiant>

  <Etudiant NInsc="S457">
    <CIN>HH9873</CIN>
    <Sexe>Feminin</Sexe>
    <Prenom>Jane</Prenom>
    <Nom>Smith</Nom>
    <Teles>
      <Tele>555-555-5555</Tele>
    </Teles>
    <Emails>
      <Email Type="Personnel">jane.smith@example.com</Email>
    </Emails>
    <dateNaiss>2000-01-01</dateNaiss>
      <adresse>
        <rue>Main Street</rue>
        <numero>123</numero>
        <ville>Cityville</ville>
      </adresse>
  </Etudiant>
</Etudiants>

<Modules>
  <Module codeModule="M123" NSom="E123">
      <Nom>Programming</Nom>
  </Module>
  <Module codeModule="M124" NSom="E123">
    <Nom>java</Nom>
</Module>
</Modules>

<Matieres>
  <Matiere NSom="E123" codeModule="M123" codeMatiere="CS101">
    <intitule>Introduction to Computer Science</intitule>
    <coeff>3</coeff>
  </Matiere>

  <Matiere NSom="E124" codeModule="M124" codeMatiere="CS102">
    <intitule>Data science</intitule>
    <coeff>2</coeff>
  </Matiere>

  <Matiere NSom="E124" codeModule="M124" codeMatiere="CS103">
    <intitule>Data</intitule>
    <coeff>4</coeff>
  </Matiere>
</Matieres>

<notes>
  <note NInsc="S456" codeMatiere="CS101">
    <NoteType>DS</NoteType>
    <valeur>85.5</valeur>
  </note>

  <note NInsc="S456" codeMatiere="CS101">
    <NoteType>Examen</NoteType>
    <valeur>18</valeur>
  </note>

  <note NInsc="S457" codeMatiere="CS101">
    <NoteType>Examen</NoteType>
    <valeur>18</valeur>
  </note>

</notes>
</Scolarite>
